package tablas;
// Generated 28-oct-2017 14:00:57 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vehiculos generated by hbm2java
 */

@Entity
@Table(name = "vehiculos")
public class Vehiculos implements java.io.Serializable {

	private String matricula;
	private String marca;
	private String modelo;
	private String imagen;
	private String averias;
	private String extras;
	private Set alquilers = new HashSet(0);

	public Vehiculos() {
	}

	public Vehiculos(String matricula, String marca, String modelo, String imagen, String averias, String extras) {
		this.matricula = matricula;
		this.marca = marca;
		this.modelo = modelo;
		this.imagen = imagen;
		this.averias = averias;
		this.extras = extras;
	}

	public Vehiculos(String matricula, String marca, String modelo, String imagen, String averias, String extras,
			Set alquilers) {
		this.matricula = matricula;
		this.marca = marca;
		this.modelo = modelo;
		this.imagen = imagen;
		this.averias = averias;
		this.extras = extras;
		this.alquilers = alquilers;
	}

	@Id
	@Column(name = "matricula")
	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	@Column(name = "marca")
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "modelo")
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "imagen")
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "averias")
	public String getAverias() {
		return this.averias;
	}

	public void setAverias(String averias) {
		this.averias = averias;
	}

	@Column(name = "extras")
	public String getExtras() {
		return this.extras;
	}

	public void setExtras(String extras) {
		this.extras = extras;
	}

	public Set getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set alquilers) {
		this.alquilers = alquilers;
	}

}
