package tablas;
// Generated 28-oct-2017 14:00:57 by Hibernate Tools 5.2.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Alquiler generated by hbm2java
 */

@Entity
@Table(name = "alquiler")
public class Alquiler implements java.io.Serializable {

	private Integer idAlquiler;
	private Usuario usuario;
	private Vehiculos vehiculos;
	private Date fechaEntrega;
	private Date fechaDevolucion;
	private float precio;

	public Alquiler() {
	}

	public Alquiler(Usuario usuario, Vehiculos vehiculos, Date fechaEntrega, Date fechaDevolucion, float precio) {
		this.usuario = usuario;
		this.vehiculos = vehiculos;
		this.fechaEntrega = fechaEntrega;
		this.fechaDevolucion = fechaDevolucion;
		this.precio = precio;
	}

	@Id
	@Column(name = "idAlquiler")
	public Integer getIdAlquiler() {
		return this.idAlquiler;
	}

	public void setIdAlquiler(Integer idAlquiler) {
		this.idAlquiler = idAlquiler;
	}

	@Column(name = "dniCliente")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "matricula")
	public Vehiculos getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Vehiculos vehiculos) {
		this.vehiculos = vehiculos;
	}

	@Column(name = "fechaEntrega")
	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	@Column(name = "fechaDevolucion")
	public Date getFechaDevolucion() {
		return this.fechaDevolucion;
	}

	public void setFechaDevolucion(Date fechaDevolucion) {
		this.fechaDevolucion = fechaDevolucion;
	}

	@Column(name = "precio")
	public float getPrecio() {
		return this.precio;
	}

	public void setPrecio(float precio) {
		this.precio = precio;
	}

}
